In [1]:
import numpy as np
import pandas as pd 
import requests

In [2]:
api = 'https://api.binance.com'
test_connection = "/api/v3/ping"
r = requests.get(api+test_connection)
r.status_code

200

In [3]:
klines = "/api/v3/klines"
params = {
    "symbol": "BTCUSDT",
    "interval": "1m",
    "limit": 10
}
r = requests.get(api+klines, params=params)
r.status_code

200

In [4]:
r.json()

[[1634392980000,
  '60848.26000000',
  '60900.00000000',
  '60848.26000000',
  '60891.01000000',
  '14.18873000',
  1634393039999,
  '863743.44152310',
  793,
  '7.09963000',
  '432175.25047460',
  '0'],
 [1634393040000,
  '60891.01000000',
  '60891.01000000',
  '60840.46000000',
  '60849.99000000',
  '14.15579000',
  1634393099999,
  '861445.32921140',
  795,
  '8.72332000',
  '530834.02588490',
  '0'],
 [1634393100000,
  '60849.99000000',
  '60850.00000000',
  '60795.22000000',
  '60849.99000000',
  '37.10800000',
  1634393159999,
  '2256856.66789890',
  1208,
  '13.85350000',
  '842582.31070370',
  '0'],
 [1634393160000,
  '60850.00000000',
  '60996.16000000',
  '60849.99000000',
  '60990.15000000',
  '39.24864000',
  1634393219999,
  '2390746.49509120',
  1033,
  '26.83731000',
  '1634638.99505100',
  '0'],
 [1634393220000,
  '60990.16000000',
  '60990.16000000',
  '60869.89000000',
  '60869.89000000',
  '22.14228000',
  1634393279999,
  '1349295.20750460',
  1044,
  '11.22645000',

In [5]:
from binance_wrapper import BinanceWrapper

binance = BinanceWrapper()
binance.test_connection()

Conexión exitosa!


In [6]:
binance.get_klines(symbol="BTCUSDT", interval="1m", limit=10)

open_time      open      high       low     close    volume  \
0 2021-10-16 11:07:00  60990.16  60990.16  60869.89  60869.89  22.14228   
1 2021-10-16 11:08:00  60869.90  61000.00  60869.89  60987.05  22.93248   
2 2021-10-16 11:09:00  60987.05  61165.77  60987.04  61101.56  67.94475   
3 2021-10-16 11:10:00  61101.57  61135.95  61049.03  61101.99  63.81655   
4 2021-10-16 11:11:00  61102.00  61134.11  61064.89  61083.03  15.61694   
5 2021-10-16 11:12:00  61083.04  61149.33  61083.01  61143.92  17.34525   
6 2021-10-16 11:13:00  61143.93  61191.88  61100.00  61189.01  44.72756   
7 2021-10-16 11:14:00  61189.01  61270.11  61148.77  61177.34  70.63815   
8 2021-10-16 11:15:00  61177.34  61219.97  61075.93  61105.36  93.70855   
9 2021-10-16 11:16:00  61105.35  61130.67  61094.28  61121.00  10.87328   

               close_time  quote_asset_vol  number_of_trades  \
0 2021-10-16 11:07:59.999     1.349295e+06              1044   
1 2021-10-16 11:08:59.999     1.397885e+06               945   
2 2021-10-16 11:09:59.999     4.151389e+06              1908   
3 2021-10-16 11:10:59.999     3.898867e+06              1566   
4 2021-10-16 11:11:59.999     9.541014e+05               982   
5 2021-10-16 11:12:59.999     1.060278e+06               984   
6 2021-10-16 11:13:59.999     2.734298e+06              1238   
7 2021-10-16 11:14:59.999     4.322995e+06              1823   
8 2021-10-16 11:15:59.999     5.729548e+06              1793   
9 2021-10-16 11:16:59.999     6.644600e+05               505   

   taker_buy_base_asset_vol  taker_buy_quote_asset_vol  
0                  11.22645               6.840626e+05  
1                   8.53310               5.201008e+05  
2                  30.91929               1.888458e+06  
3                  29.06461               1.775537e+06  
4                   7.71833               4.715361e+05  
5                   9.11851               5.573556e+05  
6                  30.53711               1.866785e+06  
7                  47.59315               2.912407e+06  
8                  39.01329               2.384854e+06  
9                   4.41142               2.695881e+05

In [7]:
import ta
import altair as alt
alt.renderers.set_embed_options(theme="dark")

RendererRegistry.enable('default')

In [8]:
dfs = []
for i in range(10):
    dfs.append(
        binance.get_klines("BTCUSDT", "4h", 1000, end_time=None if i==0 else dfs[-1].loc[0, "open_time"])
    )
btc = pd.concat(dfs)
btc.head()

open_time      open      high       low     close        volume  \
0 2021-05-02 21:00:00  56578.21  58289.99  56525.00  57925.80   9396.291029   
1 2021-05-03 01:00:00  57925.79  58848.00  57696.70  58787.87   9346.972255   
2 2021-05-03 05:00:00  58787.88  58981.44  58277.12  58657.63   9368.154323   
3 2021-05-03 09:00:00  58657.64  58770.00  57260.00  57601.83  11235.733692   
4 2021-05-03 13:00:00  57603.33  58170.00  57169.00  57564.87   8767.243395   

               close_time  quote_asset_vol  number_of_trades  \
0 2021-05-03 00:59:59.999     5.426934e+08            279773   
1 2021-05-03 04:59:59.999     5.438007e+08            329460   
2 2021-05-03 08:59:59.999     5.492032e+08            304558   
3 2021-05-03 12:59:59.999     6.519393e+08            418051   
4 2021-05-03 16:59:59.999     5.060791e+08            368455   

   taker_buy_base_asset_vol  taker_buy_quote_asset_vol  
0               4610.231642               2.662355e+08  
1               4986.298938               2.900748e+08  
2               4666.713089               2.735396e+08  
3               5275.107781               3.061433e+08  
4               4397.901503               2.538951e+08

In [9]:
btc.shape

(9112, 11)

In [10]:
btc.sort_values("close_time", ascending=True, inplace=True)
btc.reset_index(inplace=True, drop=True)
btc.head()

open_time     open     high      low    close      volume  \
0 2017-08-17 01:00:00  4261.48  4349.99  4261.32  4349.99   82.088865   
1 2017-08-17 05:00:00  4333.32  4485.39  4333.32  4427.30   63.619882   
2 2017-08-17 09:00:00  4436.06  4485.39  4333.42  4352.34  174.562001   
3 2017-08-17 13:00:00  4352.33  4354.84  4200.74  4325.23  225.109716   
4 2017-08-17 17:00:00  4307.56  4369.69  4258.56  4285.08  249.769913   

               close_time  quote_asset_vol  number_of_trades  \
0 2017-08-17 04:59:59.999     3.531943e+05               334   
1 2017-08-17 08:59:59.999     2.825012e+05               248   
2 2017-08-17 12:59:59.999     7.742388e+05               858   
3 2017-08-17 16:59:59.999     9.652911e+05               986   
4 2017-08-17 20:59:59.999     1.079545e+06              1001   

   taker_buy_base_asset_vol  taker_buy_quote_asset_vol  
0                 64.013727              275647.421911  
1                 58.787633              261054.051154  
2                125.184133              555419.758061  
3                165.036363              707808.200922  
4                203.226685              878286.968557

In [11]:
btc.tail()

open_time      open      high       low     close  \
9107 2021-10-15 17:00:00  61446.33  62933.00  60797.01  61672.42   
9108 2021-10-15 21:00:00  61672.42  61771.65  61120.00  61655.99   
9109 2021-10-16 01:00:00  61655.99  62378.42  61551.31  61733.96   
9110 2021-10-16 05:00:00  61733.96  62062.55  61324.79  61597.26   
9111 2021-10-16 09:00:00  61597.26  61605.81  60398.73  61118.87   

            volume              close_time  quote_asset_vol  number_of_trades  \
9107  15208.046405 2021-10-15 20:59:59.999     9.405609e+08            585958   
9108   5588.918910 2021-10-16 00:59:59.999     3.434696e+08            193770   
9109   5511.081480 2021-10-16 04:59:59.999     3.414945e+08            245427   
9110   7202.455500 2021-10-16 08:59:59.999     4.437385e+08            268083   
9111   6704.100550 2021-10-16 12:59:59.999     4.087163e+08            238147   

      taker_buy_base_asset_vol  taker_buy_quote_asset_vol  
9107               7846.495834               4.853944e+08  
9108               2646.060870               1.626089e+08  
9109               2845.349590               1.763184e+08  
9110               3706.455000               2.283374e+08  
9111               3108.303650               1.894898e+08

In [12]:
btc_resampled = btc.groupby(btc.index // 6).agg(
    {
        "close_time": [("close_time", "last")],
        "close": [("close", "last")], 
        "high": [("high", "last")],
        "open": [("open", "last")],
        "low": [("low", "last")],
    }
).droplevel(0, axis=1)

btc_resampled.loc[:, "return"] = btc_resampled.loc[:, "close"].pct_change()

btc_resampled.head()

close_time    close     high     open      low    return
0 2017-08-18 00:59:59.999  4292.39  4340.62  4285.08  4134.61       NaN
1 2017-08-19 00:59:59.999  4138.55  4184.69  4108.37  4084.28 -0.035840
2 2017-08-20 00:59:59.999  4094.62  4139.98  4120.98  4044.00 -0.010615
3 2017-08-21 00:59:59.999  4084.76  4119.62  4069.13  4039.00 -0.002408
4 2017-08-22 00:59:59.999  3862.39  4016.00  4016.00  3688.97 -0.054439

In [13]:
c = alt.Chart(btc_resampled.reset_index())

c1 = c.mark_line().encode(
    x = alt.X("close_time:T", title="Date"),
    y = alt.Y("close:Q", title="Price"),
    tooltip = ["open:Q", "low:Q", "high:Q", "close:Q"]
).interactive()

c2 = c.mark_bar().encode(
    x = alt.X("return:Q", bin=alt.Bin(maxbins=60), title="Return"),
    y = alt.Y("count()", title="Count")
).interactive()

c3 = c.mark_rule(color="red").encode(
    x="mean(return):Q",
    size=alt.value(2),
    tooltip=["mean(return):Q"]
)

c1 | c2 + c3

alt.HConcatChart(...)

In [14]:
btc = ta.add_all_ta_features(
    btc, open="open", high="high", low="low", close="close", volume="volume"
)

C:\Users\matim\.conda\envs\tf-gpu\lib\site-packages\ta\trend.py:768: RuntimeWarning: invalid value encountered in double_scalars
  dip[i] = 100 * (self._dip[i] / self._trs[i])
C:\Users\matim\.conda\envs\tf-gpu\lib\site-packages\ta\trend.py:772: RuntimeWarning: invalid value encountered in double_scalars
  din[i] = 100 * (self._din[i] / self._trs[i])


In [15]:
btc.shape

(9112, 94)

In [16]:
btc.columns

Index(['open_time', 'open', 'high', 'low', 'close', 'volume', 'close_time',
       'quote_asset_vol', 'number_of_trades', 'taker_buy_base_asset_vol',
       'taker_buy_quote_asset_vol', 'volume_adi', 'volume_obv', 'volume_cmf',
       'volume_fi', 'volume_mfi', 'volume_em', 'volume_sma_em', 'volume_vpt',
       'volume_nvi', 'volume_vwap', 'volatility_atr', 'volatility_bbm',
       'volatility_bbh', 'volatility_bbl', 'volatility_bbw', 'volatility_bbp',
       'volatility_bbhi', 'volatility_bbli', 'volatility_kcc',
       'volatility_kch', 'volatility_kcl', 'volatility_kcw', 'volatility_kcp',
       'volatility_kchi', 'volatility_kcli', 'volatility_dcl',
       'volatility_dch', 'volatility_dcm', 'volatility_dcw', 'volatility_dcp',
       'volatility_ui', 'trend_macd', 'trend_macd_signal', 'trend_macd_diff',
       'trend_sma_fast', 'trend_sma_slow', 'trend_ema_fast', 'trend_ema_slow',
       'trend_adx', 'trend_adx_pos', 'trend_adx_neg', 'trend_vortex_ind_pos',
       'trend_vortex_ind

In [17]:
cols = ["volume_mfi", "trend_macd", "trend_macd_signal", "momentum_rsi"]
btc.loc[:, cols].isna().sum()

volume_mfi           13
trend_macd           25
trend_macd_signal    33
momentum_rsi         13
dtype: int64

In [18]:
def create_target(x:pd.Series, low:float, high:float)->int:
    cum_ret = (1. + x.pct_change().fillna(0.)).cumprod()
    if np.any(cum_ret >= high):
        return 1
    elif np.any(cum_ret <= low):
        return -1
    else:
        return 0

In [19]:
btc_transformed = btc.groupby(btc.index//6).agg(
    {
        "close_time": [("close_time", "first")],
        "volume_mfi": [("volume_mfi", "first")],
        "trend_macd": [("trend_macd", "first")],
        "trend_macd_signal": [("trend_macd_signal", "first")],
        "momentum_rsi": [("momentum_rsi", "first")],
        "close": [("target", lambda x: create_target(x, 0.995, 1.005))],
    }
).droplevel(0, axis=1)

btc_transformed.dropna(inplace=True)
btc_transformed.reset_index(drop=True, inplace=True)
btc_transformed.head()

close_time  volume_mfi  trend_macd  trend_macd_signal  \
0 2017-08-22 04:59:59.999   28.462600  -84.409574         -75.944425   
1 2017-08-23 04:59:59.999   53.509385  -44.851456         -65.751863   
2 2017-08-24 04:59:59.999   66.409823    7.229003         -18.271895   
3 2017-08-25 04:59:59.999   72.096742   55.756375          24.933765   
4 2017-08-26 04:59:59.999   83.321226   62.283063          54.735036   

   momentum_rsi  target  
0     24.179934       1  
1     51.568960       1  
2     55.026141       1  
3     65.721835       1  
4     60.014633      -1

In [20]:
btc_transformed.loc[:, "target"].value_counts()

 1    916
-1    523
 0     75
Name: target, dtype: int64

In [21]:
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
train_index = round(0.7*len(btc_transformed))
X_train = btc_transformed.iloc[:train_index].drop(["close_time", "target"], axis=1)
y_train = label_encoder.fit_transform(btc_transformed.iloc[:train_index]["target"])
y_train_cat = to_categorical(y_train, num_classes=3)

In [22]:
label_encoder.transform([-1, 0, 1])

array([0, 1, 2], dtype=int64)

In [23]:
y_train[:5]

array([2, 2, 2, 2, 0], dtype=int64)

In [24]:
y_train_cat[:5]

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [25]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [26]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(
    Dense(8, batch_input_shape=(None, X_train.shape[1]), activation="relu")
)
model.add(
    Dense(
        3, 
        activation="softmax"
    )
)

model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [27]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 27        
Total params: 67
Trainable params: 67
Non-trainable params: 0
_________________________________________________________________


In [28]:
history = model.fit(X_train_scaled, y_train_cat, batch_size=16, epochs=200, verbose=1)

Epoch 1/200
67/67 [==============================] - 0s 789us/step - loss: 1.1709 - accuracy: 0.2708
Epoch 2/200
67/67 [==============================] - 0s 682us/step - loss: 1.0197 - accuracy: 0.4915
Epoch 3/200
67/67 [==============================] - 0s 682us/step - loss: 0.9439 - accuracy: 0.5651
Epoch 4/200
67/67 [==============================] - 0s 652us/step - loss: 0.9032 - accuracy: 0.5764
Epoch 5/200
67/67 [==============================] - 0s 682us/step - loss: 0.8803 - accuracy: 0.5774
Epoch 6/200
67/67 [==============================] - 0s 698us/step - loss: 0.8672 - accuracy: 0.5783
Epoch 7/200
67/67 [==============================] - 0s 727us/step - loss: 0.8599 - accuracy: 0.5774
Epoch 8/200
67/67 [==============================] - 0s 713us/step - loss: 0.8543 - accuracy: 0.5783
Epoch 9/200
67/67 [==============================] - 0s 644us/step - loss: 0.8509 - accuracy: 0.5783
Epoch 10/200
67/67 [==============================] - 0s 652us/step - loss: 0.8491 - accura

In [33]:
np.argmax(model.predict(X_train_scaled), axis=1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [34]:
from sklearn.metrics import classification_report

y_pred = np.argmax(model.predict(X_train_scaled), axis=1)

print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       381
           1       0.00      0.00      0.00        67
           2       0.58      1.00      0.73       612

    accuracy                           0.58      1060
   macro avg       0.19      0.33      0.24      1060
weighted avg       0.33      0.58      0.42      1060



C:\Users\matim\.conda\envs\tf-gpu\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\matim\.conda\envs\tf-gpu\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\matim\.conda\envs\tf-gpu\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [35]:
btc_train_results = btc_transformed.iloc[:train_index].copy()
btc_train_results.head()

close_time  volume_mfi  trend_macd  trend_macd_signal  \
0 2017-08-22 04:59:59.999   28.462600  -84.409574         -75.944425   
1 2017-08-23 04:59:59.999   53.509385  -44.851456         -65.751863   
2 2017-08-24 04:59:59.999   66.409823    7.229003         -18.271895   
3 2017-08-25 04:59:59.999   72.096742   55.756375          24.933765   
4 2017-08-26 04:59:59.999   83.321226   62.283063          54.735036   

   momentum_rsi  target  
0     24.179934       1  
1     51.568960       1  
2     55.026141       1  
3     65.721835       1  
4     60.014633      -1

In [36]:
btc_train_results.loc[:, ["prob_0", "prob_1", "prob_2"]] = model.predict(X_train_scaled)
btc_train_results.head()

close_time  volume_mfi  trend_macd  trend_macd_signal  \
0 2017-08-22 04:59:59.999   28.462600  -84.409574         -75.944425   
1 2017-08-23 04:59:59.999   53.509385  -44.851456         -65.751863   
2 2017-08-24 04:59:59.999   66.409823    7.229003         -18.271895   
3 2017-08-25 04:59:59.999   72.096742   55.756375          24.933765   
4 2017-08-26 04:59:59.999   83.321226   62.283063          54.735036   

   momentum_rsi  target    prob_0    prob_1    prob_2  
0     24.179934       1  0.368805  0.042484  0.588711  
1     51.568960       1  0.353151  0.086003  0.560846  
2     55.026141       1  0.270613  0.149934  0.579453  
3     65.721835       1  0.299923  0.118168  0.581909  
4     60.014633      -1  0.248148  0.063084  0.688768

In [37]:
btc_train_results.loc[:, "prob_2_bin"] = pd.qcut(btc_train_results.loc[:, "prob_2"], q=10)
btc_train_results.loc[:, "prob_2_bin"] = btc_train_results.loc[:, "prob_2_bin"].astype(str)
btc_train_agg = btc_train_results.groupby("prob_2_bin").agg(
    {
        "target": [("success_rate", lambda x: (x==1).sum()/len(x)), ("count", lambda x: (x==1).sum())]
    }
    ).droplevel(0,axis=1).reset_index()

In [38]:
btc_train_agg

prob_2_bin  success_rate  count
0  (0.457, 0.493]      0.424528     45
1  (0.493, 0.523]      0.481132     51
2  (0.523, 0.542]      0.481132     51
3  (0.542, 0.556]      0.528302     56
4  (0.556, 0.571]      0.556604     59
5  (0.571, 0.586]      0.556604     59
6  (0.586, 0.605]      0.679245     72
7  (0.605, 0.624]      0.735849     78
8  (0.624, 0.661]      0.698113     74
9  (0.661, 0.859]      0.632075     67

In [39]:
alt.Chart(btc_train_agg).mark_bar().encode(
    x=alt.X("prob_2_bin", title="P(X>1.005)"),
    y=alt.Y("success_rate:Q", title="Success Rate"),
    tooltip=["count:Q"]
).properties(
    width=600
)

alt.Chart(...)